#ifndef INLINE4_LZO_H
#define INLINE4_LZO_H

/*
** This file was auto generated by idltool 53.23.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_LZO_H
#include <libraries/lzo.h>
#endif
#include <interfaces/lzo.h>

/* Inline macros for Interface "main" */
#define lzo1_mem_compress() ILZO->lzo1_mem_compress()
#define lzo1_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1_mem_decompress() ILZO->lzo1_mem_decompress()
#define lzo1_decompress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1_decompress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1_99_mem_compress() ILZO->lzo1_99_mem_compress()
#define lzo1_99_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1_99_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1a_mem_compress() ILZO->lzo1a_mem_compress()
#define lzo1a_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1a_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1a_mem_decompress() ILZO->lzo1a_mem_decompress()
#define lzo1a_decompress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1a_decompress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1a_99_mem_compress() ILZO->lzo1a_99_mem_compress()
#define lzo1a_99_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1a_99_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1b_mem_compress() ILZO->lzo1b_mem_compress()
#define lzo1b_compress(src, src_len, dst, dst_len, wrkmem, clevel) ILZO->lzo1b_compress((src), (src_len), (dst), (dst_len), (wrkmem), (clevel))
#define lzo1b_mem_decompress() ILZO->lzo1b_mem_decompress()
#define lzo1b_decompress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1b_decompress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1b_decompress_safe(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1b_decompress_safe((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1b_99_mem_compress() ILZO->lzo1b_99_mem_compress()
#define lzo1b_99_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1b_99_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1b_999_mem_compress() ILZO->lzo1b_999_mem_compress()
#define lzo1b_999_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1b_999_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1c_mem_compress() ILZO->lzo1c_mem_compress()
#define lzo1c_compress(src, src_len, dst, dst_len, wrkmem, clevel) ILZO->lzo1c_compress((src), (src_len), (dst), (dst_len), (wrkmem), (clevel))
#define lzo1c_mem_decompress() ILZO->lzo1c_mem_decompress()
#define lzo1c_decompress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1c_decompress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1c_decompress_safe(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1c_decompress_safe((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1c_99_mem_compress() ILZO->lzo1c_99_mem_compress()
#define lzo1c_99_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1c_99_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1c_999_mem_compress() ILZO->lzo1c_999_mem_compress()
#define lzo1c_999_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1c_999_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1f_mem_compress() ILZO->lzo1f_mem_compress()
#define lzo1f_1_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1f_1_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1f_mem_decompress() ILZO->lzo1f_mem_decompress()
#define lzo1f_decompress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1f_decompress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1f_decompress_safe(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1f_decompress_safe((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1f_999_mem_compress() ILZO->lzo1f_999_mem_compress()
#define lzo1f_999_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1f_999_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1x_mem_compress() ILZO->lzo1x_mem_compress()
#define lzo1x_1_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1x_1_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1x_mem_decompress() ILZO->lzo1x_mem_decompress()
#define lzo1x_decompress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1x_decompress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1x_decompress_safe(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1x_decompress_safe((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1x_1_11_mem_compress() ILZO->lzo1x_1_11_mem_compress()
#define lzo1x_1_11_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1x_1_11_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1x_1_12_mem_compress() ILZO->lzo1x_1_12_mem_compress()
#define lzo1x_1_12_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1x_1_12_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1x_1_15_mem_compress() ILZO->lzo1x_1_15_mem_compress()
#define lzo1x_1_15_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1x_1_15_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1x_999_mem_compress() ILZO->lzo1x_999_mem_compress()
#define lzo1x_999_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1x_999_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1x_999_compress_dict(src, src_len, dst, dst_len, wrkmem, dict, dict_len) ILZO->lzo1x_999_compress_dict((src), (src_len), (dst), (dst_len), (wrkmem), (dict), (dict_len))
#define lzo1x_999_compress_level(src, src_len, dst, dst_len, wrkmem, dict, dict_len, cb, clevel) ILZO->lzo1x_999_compress_level((src), (src_len), (dst), (dst_len), (wrkmem), (dict), (dict_len), (cb), (clevel))
#define lzo1x_decompress_dict_safe(src, src_len, dst, dst_len, wrkmem, dict, dict_len) ILZO->lzo1x_decompress_dict_safe((src), (src_len), (dst), (dst_len), (wrkmem), (dict), (dict_len))
#define lzo1x_mem_optimize() ILZO->lzo1x_mem_optimize()
#define lzo1x_optimize(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1x_optimize((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1y_mem_compress() ILZO->lzo1y_mem_compress()
#define lzo1y_1_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1y_1_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1y_mem_decompress() ILZO->lzo1y_mem_decompress()
#define lzo1y_decompress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1y_decompress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1y_decompress_safe(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1y_decompress_safe((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1y_999_mem_compress() ILZO->lzo1y_999_mem_compress()
#define lzo1y_999_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1y_999_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1y_999_compress_dict(src, src_len, dst, dst_len, wrkmem, dict, dict_len) ILZO->lzo1y_999_compress_dict((src), (src_len), (dst), (dst_len), (wrkmem), (dict), (dict_len))
#define lzo1y_999_compress_level(src, src_len, dst, dst_len, wrkmem, dict, dict_len, cb, clevel) ILZO->lzo1y_999_compress_level((src), (src_len), (dst), (dst_len), (wrkmem), (dict), (dict_len), (cb), (clevel))
#define lzo1y_decompress_dict_safe(src, src_len, dst, dst_len, wrkmem, dict, dict_len) ILZO->lzo1y_decompress_dict_safe((src), (src_len), (dst), (dst_len), (wrkmem), (dict), (dict_len))
#define lzo1y_mem_optimize() ILZO->lzo1y_mem_optimize()
#define lzo1y_optimize(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1y_optimize((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1z_mem_decompress() ILZO->lzo1z_mem_decompress()
#define lzo1z_decompress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1z_decompress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1z_decompress_safe(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1z_decompress_safe((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1z_999_mem_compress() ILZO->lzo1z_999_mem_compress()
#define lzo1z_999_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo1z_999_compress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo1z_999_compress_dict(src, src_len, dst, dst_len, wrkmem, dict, dict_len) ILZO->lzo1z_999_compress_dict((src), (src_len), (dst), (dst_len), (wrkmem), (dict), (dict_len))
#define lzo1z_999_compress_level(src, src_len, dst, dst_len, wrkmem, dict, dict_len, cb, clevel) ILZO->lzo1z_999_compress_level((src), (src_len), (dst), (dst_len), (wrkmem), (dict), (dict_len), (cb), (clevel))
#define lzo1z_decompress_dict_safe(src, src_len, dst, dst_len, wrkmem, dict, dict_len) ILZO->lzo1z_decompress_dict_safe((src), (src_len), (dst), (dst_len), (wrkmem), (dict), (dict_len))
#define lzo2a_mem_decompress() ILZO->lzo2a_mem_decompress()
#define lzo2a_decompress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo2a_decompress((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo2a_decompress_safe(src, src_len, dst, dst_len, wrkmem) ILZO->lzo2a_decompress_safe((src), (src_len), (dst), (dst_len), (wrkmem))
#define lzo2a_999_mem_compress() ILZO->lzo2a_999_mem_compress()
#define lzo2a_999_compress(src, src_len, dst, dst_len, wrkmem) ILZO->lzo2a_999_compress((src), (src_len), (dst), (dst_len), (wrkmem))

#endif /* INLINE4_LZO_H */
